
    - name: NAT outside sur GigabitEthernet1
      cisco.ios.ios_config:
        lines:
          - ip nat outside
        parents: interface GigabitEthernet1

    - name: NAT inside sur interfaces LAN
      cisco.ios.ios_config:
        lines:
          - ip nat inside
        parents: "interface {{ item }}"
      loop:
        - GigabitEthernet2
        - GigabitEthernet3
        - GigabitEthernet4

    - name: ACL et NAT dynamique
      cisco.ios.ios_config:
        lines:
          - access-list 1 permit 192.168.0.0 0.0.255.255
          - ip nat inside source list 1 interface GigabitEthernet1 overload
